# Generated by Django 4.0.3 on 2022-04-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0001_Creacion_Tabla_Usuarios'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
