# Generated by Django 4.0.3 on 2022-04-19 02:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_Agrege_Cloudinary_Foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('foto', cloudinary.models.CloudinaryField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('precio_diario', models.FloatField()),
                ('platoId', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='menu.plato')),
            ],
            options={
                'db_table': 'stocks',
                'unique_together': {('fecha', 'platoId')},
            },
        ),
    ]
