# Generated by Django 4.0.3 on 2022-04-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_Agrege_Stock_Model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='foto',
        ),
    ]
